//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Приятный_шелест.Enitities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENTHISTORY
    {
        public int ID { get; set; }
        public int PRIORITY { get; set; }
        public Nullable<int> AGENTID { get; set; }
    
        public virtual AGENT AGENT { get; set; }
    }
}
