//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Приятный_шелест.Enitities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AGENT()
        {
            this.AGENTHISTORY = new HashSet<AGENTHISTORY>();
            this.SALECONTRACT = new HashSet<SALECONTRACT>();
        }
    
        public int ID { get; set; }
        public int AGENTTYPEID { get; set; }
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public string PHOTOPATH { get; set; }
        public string BUSINESSADDRESS { get; set; }
        public string DIRECTORLASTNAME { get; set; }
        public string DIRECTORFIRSTNAME { get; set; }
        public string DIRECTORMIDDLENAME { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
    
        public virtual AGENTTYPE AGENTTYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGENTHISTORY> AGENTHISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALECONTRACT> SALECONTRACT { get; set; }
    }
}
