//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Приятный_шелест.Enitities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user8Entities : DbContext
    {
        public user8Entities()
            : base("name=user8Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGENT> AGENT { get; set; }
        public virtual DbSet<AGENTHISTORY> AGENTHISTORY { get; set; }
        public virtual DbSet<AGENTTYPE> AGENTTYPE { get; set; }
        public virtual DbSet<CATEGORY> CATEGORY { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEE { get; set; }
        public virtual DbSet<GOOD> GOOD { get; set; }
        public virtual DbSet<GOODPARAMETR> GOODPARAMETR { get; set; }
        public virtual DbSet<GOODTYPE> GOODTYPE { get; set; }
        public virtual DbSet<INFORMATION> INFORMATION { get; set; }
        public virtual DbSet<PARAMETER> PARAMETER { get; set; }
        public virtual DbSet<PROVIDER> PROVIDER { get; set; }
        public virtual DbSet<PROVIDERGOOD> PROVIDERGOOD { get; set; }
        public virtual DbSet<ROLE> ROLE { get; set; }
        public virtual DbSet<SALECONTRACT> SALECONTRACT { get; set; }
        public virtual DbSet<SUPPLY> SUPPLY { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<USER> USER { get; set; }
        public virtual DbSet<VISIT> VISIT { get; set; }
    }
}
