//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Приятный_шелест.Enitities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOOD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GOOD()
        {
            this.GOODPARAMETR = new HashSet<GOODPARAMETR>();
            this.PROVIDERGOOD = new HashSet<PROVIDERGOOD>();
            this.SALECONTRACT = new HashSet<SALECONTRACT>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> GOODTYPEID { get; set; }
        public string ARTICLE { get; set; }
        public int PEOPLECOUNT { get; set; }
        public int FLOORNUMBER { get; set; }
        public decimal MINPRICE { get; set; }
    
        public virtual GOODTYPE GOODTYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOODPARAMETR> GOODPARAMETR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROVIDERGOOD> PROVIDERGOOD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALECONTRACT> SALECONTRACT { get; set; }
    }
}
