//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Приятный_шелест.Enitities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOODPARAMETR
    {
        public int ID { get; set; }
        public int GOODID { get; set; }
        public int PARAMETERID { get; set; }
        public string VALUE { get; set; }
    
        public virtual GOOD GOOD { get; set; }
        public virtual PARAMETER PARAMETER { get; set; }
    }
}
