//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Приятный_шелест.Enitities
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORMATION
    {
        public int ID { get; set; }
        public int EMPLOYEEID { get; set; }
        public int CATEGORYID { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
