//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Приятный_шелест.Enitities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALECONTRACT
    {
        public int ID { get; set; }
        public int GOODID { get; set; }
        public Nullable<int> AGENTID { get; set; }
        public System.DateTime DATE { get; set; }
        public int COUNT { get; set; }
        public Nullable<bool> COMPLETE { get; set; }
        public Nullable<int> EMPLOYEEID { get; set; }
    
        public virtual AGENT AGENT { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual GOOD GOOD { get; set; }
    }
}
