//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Приятный_шелест.Enitities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLY
    {
        public int ID { get; set; }
        public Nullable<int> PROVIDERPRODUCTID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public int COUNT { get; set; }
    
        public virtual PROVIDERGOOD PROVIDERGOOD { get; set; }
    }
}
