//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Train
{
    using System;
    using System.Collections.Generic;
    
    public partial class Src
    {
        public int Id { get; set; }
        public Nullable<int> TypesUsers_Id { get; set; }
        public string Src1 { get; set; }
    
        public virtual TypesUsers TypesUsers { get; set; }
    }
}
