//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchet_Zayavok.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otchet
    {
        public int ID { get; set; }
        public int Time { get; set; }
        public string Material { get; set; }
        public int Cost { get; set; }
        public string ReasonNeisp { get; set; }
        public string OpisanieHelp { get; set; }
        public int ZayavkaID { get; set; }
        public int IspolnitelID { get; set; }
        public Nullable<int> ZapchastID { get; set; }
    }
}
