-- ---------------------------------------------------
--
-- SQL script generated by Red Expert.
-- Generated 21-Apr-2024 8:06:07
--
-- ---------------------------------------------------
--
-- Program:      script Доставка товаров.sql
-- Description:  SQL create tables script.
-- Schema:       Not Available
-- Database:     Not Available
--
-- ---------------------------------------------------



CREATE TABLE USER_ROLE (USER_ROLE_ID     INTEGER NOT NULL,
                        "NAME"             VARCHAR(100) NOT NULL,
                        CONSTRAINT PK_USER_ROLE_ID PRIMARY KEY (USER_ROLE_ID));


CREATE TABLE USERS (USER_ID         INTEGER NOT NULL,
                    LAST_NAME       VARCHAR(100) NOT NULL,
                    FIRST_NAME      VARCHAR(100) NOT NULL,
                    MIDDLE_NAME     VARCHAR(100) NOT NULL,
                    LOGIN           VARCHAR(100) NOT NULL,
                    "PASSWORD"        VARCHAR(100) NOT NULL,
                    STATUS          VARCHAR(100) NOT NULL,
                    USER_ROLE       INTEGER NOT NULL,
                    CONSTRAINT PK_User_ID PRIMARY KEY (USER_ID),
                    CONSTRAINT FK_User_Role_ID FOREIGN KEY (USER_ROLE) REFERENCES USER_ROLE(USER_ROLE_ID));


CREATE TABLE ORDERS (ORDER_ID           INTEGER NOT NULL,
                     "DATE"               DATE NOT NULL,
                     ORDER_STATUS       VARCHAR(100) NOT NULL,
                     PAYMENT_STATUS     VARCHAR(100) NOT NULL,
                     ADDRESS            VARCHAR(100) NOT NULL,
                     FIO_CLIENTS        VARCHAR(100) NOT NULL,
                     PAYMENT_FORM       VARCHAR(100) NOT NULL,
                     CONSTRAINT PK_Order_ID PRIMARY KEY (ORDER_ID));


CREATE TABLE STAFF_LIST (STAFF_LIST_ID     INTEGER NOT NULL,
                         STAFF_NUMBER      INTEGER NOT NULL,
                         TIME_START        TIME,
                         TIME_END          TIME,
                         CONSTRAINT PK_Staff_List_ID PRIMARY KEY (STAFF_LIST_ID));


CREATE TABLE USER_STAFF_LIST (USER_STAFF_LIST_ID     INTEGER NOT NULL,
                              USER_ID                INTEGER NOT NULL,
                              U_STAFF_LIST_ID        INTEGER NOT NULL,
                              CONSTRAINT PK_User_Staff_List PRIMARY KEY (USER_STAFF_LIST_ID),
                              CONSTRAINT FK_User_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
                              CONSTRAINT FK_U_Staff_List_ID FOREIGN KEY (U_STAFF_LIST_ID) REFERENCES STAFF_LIST(STAFF_LIST_ID));


CREATE TABLE ORDER_STAFF_LIST (ORDER_STAFF_LIST_ID     INTEGER NOT NULL,
                               STAFF_LIST_ID           INTEGER NOT NULL,
                               ORDER_ID                INTEGER NOT NULL,
                               CONSTRAINT PK_Order_Staff_List_ID PRIMARY KEY (ORDER_STAFF_LIST_ID),
                               CONSTRAINT FK_Staff_List_ID FOREIGN KEY (STAFF_LIST_ID) REFERENCES STAFF_LIST(STAFF_LIST_ID),
                               CONSTRAINT FK_Order_ID FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID));


