//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPKiO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderServises = new HashSet<OrderServise>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public System.DateTime creation_date { get; set; }
        public System.TimeSpan creation_time { get; set; }
        public int client_id { get; set; }
        public int status_id { get; set; }
        public Nullable<System.DateTime> closing_date { get; set; }
        public int rental_time { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderServise> OrderServises { get; set; }
    }
}
