//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPKiO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int id { get; set; }
        public int role_id { get; set; }
        public string name { get; set; }
        public string photo { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> last_entry { get; set; }
        public int successful_entry { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
